language: node_js
node_js:
- 11.12.0
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
scripts:
  - npm run build
  - echo "npm test temporarily disabled"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master