language: node_js
node_js:
  - 11.12.0
install:
  - npm ci
cache:
  directories:
  - "$HOME/.npm"
scripts:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  keep_history: true
  local_dir: build
  on:
    branch: master