version: '3'

services:
  afterimage-frontend:
    build: .
    command: npm start
    volumes:
      - .:/usr/afterimage-frontend
      - /usr/afterimage-frontend/node_modules
    ports:
      - "3000:3000"
